// This file was generated by Prisma.
// In Render, DATABASE_URL is provided via environment variables.
// Load dotenv only when it is available locally.
import { defineConfig } from "@prisma/config";

try {
  require("dotenv/config");
} catch (error) {
  // dotenv is optional in Render production environments.
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
